#!/bin/sh

ctrl_c() {
	printf '\nAborted\n\n'
	exit 1
}

trap ctrl_c INT

mkdir -v ~/.steam
ln -sfv ~/.steam ~/.steam/steam

cd ~/.steam || exit

for arc in /tmp/cs16-server/*.tar.*; do tar xvf "$arc"; done

mkdir -pv addons/metamod/dlls
mv -vf metamod.* addons/metamod/dlls

cnt=0
while [ $((cnt)) -lt 3 ]; do
	# Update needs to be run a few times to download and validate everything
	./steamcmd.sh +force_install_dir cs16 +login anonymous +app_update 90 validate +quit
	cnt=$((cnt+1))
done

mv -vf addons cs16/cstrike
ln -sfv ~/.steam/linux32 ~/.steam/sdk32

printf 'linux addons/amxmodx/dlls/amxmodx_mm_i386.so\n' >> cs16/cstrike/addons/metamod/plugins.ini
printf 'linux addons/yapb/bin/yapb.so\n' >> cs16/cstrike/addons/metamod/plugins.ini

# Create cfg files so steamcmd won't complain
touch cs16/cstrike/listip.cfg
touch cs16/cstrike/banned.cfg

cp -vf /tmp/install-maps-and-graphs ~/
