#!/bin/sh

server_user=hlds

cd "/home/$server_user/" || exit
mkdir -v .steam
cd .steam || exit
ln -sfv . steam

for arc in /tmp/cs16-server/*.tar.*; do tar xvf "$arc"; done

mkdir -pv addons/metamod/dlls
mv -vf metamod.* addons/metamod/dlls

printf 'linux addons/amxmodx/dlls/amxmodx_mm_i386.so\n' > addons/metamod/plugins.ini
printf ';;linux addons/yapb/bin/yapb.so\n' >> addons/metamod/plugins.ini

cnt=0
while [ $((cnt)) -lt 3 ]; do
	# Update needs to be run a few times to download and validate everything
	./steamcmd.sh +force_install_dir cs16 +login anonymous +app_update 90 validate +quit
	cnt=$((cnt+1))
done

mv -vf addons cs16/cstrike
ln -sfv linux32 sdk32

# Create cfg files so steamcmd won't complain
touch cs16/cstrike/listip.cfg
touch cs16/cstrike/banned.cfg
