#!/bin/bash

if [[ "$(id -u)" -ne 0 ]]; then
    printf "This script must be run as root\n"
    printf "Pass \"remove\" arg to uninstall\n"
    exit 1
fi

export server_user="hlds"
export tmp_dir="/tmp/cs16-server"

abort_install() {
    pgrep steamcmd > /dev/null 2>&1 && pkill -SIGINT steamcmd > /dev/null 2>&1
    printf "\nInstallation aborted\n"
    exit 1
}

trap abort_install INT TERM ERR

remove_server() {
    if pgrep -u "${server_user}" > /dev/null 2>&1; then
        printf "%s user has processes running\n" "${server_user}"
        printf "Stop them before uninstalling the server\n"
        exit 1
    fi

    userdel -r "${server_user}" && printf "User %s deleted\n" "${server_user}"

    rm -vrf /etc/hlds
    rm -vf /usr/bin/cs16-server
    rm -vf /usr/share/man/man1/cs16-server.1*

    [[ -x "$(command -v systemctl)" ]] && rm -vf /usr/lib/systemd/system/cs16-server.service
}

check_depends() {
    if [[ -d "/home/${server_user}" ]]; then
        printf "Server is already installed\n"
        exit 1
    fi

    if ! ldconfig -p | grep -q 'libstdc++.so.6.(libc6)'; then
        printf "Install 32-bit libstdc++\n"
        printf "See README.md for details\n"
        exit 1
    fi

    pkgs=("tar" "xz" "gzip" "curl")
    missing_pkgs=""

    [[ ! -x "$(command -v sestatus)" ]] && missing_pkgs=" policycoreutils-python-utils"

    for pkg in "${pkgs[@]}"; do
        [[ -x "$(command -v "${pkg}")" ]] || missing_pkgs="${missing_pkgs} ${pkg}"
    done

    if [[ -n "${missing_pkgs}" ]]; then
        printf "Install the following packages:%s\n" "${missing_pkgs}"
        exit 1
    fi
}

install_stage_one() {
    [[ -d "${tmp_dir}" ]] && rm -vrf "${tmp_dir}"

    mkdir -vp "${tmp_dir}"
    pushd "${tmp_dir}" || exit 1

    links=(
        "https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz"
        "https://github.com/Bots-United/metamod-p/releases/download/v1.21p38/metamod_i686_linux_win32-1.21p38.tar.xz"
        "https://www.amxmodx.org/amxxdrop/1.10/amxmodx-1.10.0-git5467-base-linux.tar.gz"
        "https://www.amxmodx.org/amxxdrop/1.10/amxmodx-1.10.0-git5467-cstrike-linux.tar.gz"
        "https://github.com/yapb/yapb/releases/download/4.4.957/yapb-4.4.957-linux.tar.xz"
    )

    for link in "${links[@]}"; do
        printf "==> Downloading %s\n" "${link}"
        if ! curl -fLO "${link}"; then
            printf "Failed to download %s\n" "${link}"
            exit 1
        fi
    done

    popd || exit 1

    useradd -m -s "$(command -v bash)" "${server_user}"
}

install_stage_two() {
    mkdir -vp "/home/${server_user}/.steam"
    cd "/home/${server_user}/.steam" || exit 1
    ln -sfv . steam

    for arc in "${tmp_dir}/"*.tar.*; do
        tar xvf "${arc}"
    done

    # Needs to be run a few times to download and validate everything
    for _i in {1..3}; do
        ./steamcmd.sh +force_install_dir cs16 +login anonymous +app_update 90 validate +quit
    done

    # Temporary fix for 4.4.957
    chmod -v 755 addons/yapb/data/*

    mv -vf addons cs16/cstrike

    mkdir -vp cs16/cstrike/addons/metamod/dlls
    mv -vf metamod.so cs16/cstrike/addons/metamod/dlls
    # Remove part for Windows
    rm -vf metamod.dll

    # amxmodx: on
    # yapb bots: off
    printf "linux addons/amxmodx/dlls/amxmodx_mm_i386.so\n" > cs16/cstrike/addons/metamod/plugins.ini
    printf ";;linux addons/yapb/bin/yapb.so\n" >> cs16/cstrike/addons/metamod/plugins.ini

    ln -sfv linux32 sdk32
    # Create empty files so hlds_run won't complain
    touch cs16/cstrike/{listip.cfg,banned.cfg}
}

install_stage_three(){
    install -vm 755 cs16-server/cs16-server -t /usr/bin
    install -vDm 644 cs16-server/cs16-server.conf -t /etc/hlds
    install -vm 644 cs16-server/cs16-server.1 -t /usr/share/man/man1
    gzip -vf --best /usr/share/man/man1/cs16-server.1
}

install_service() {
    install -m 644 cs16-server/cs16-server.service -t /usr/lib/systemd/system
    printf "\nRun \"systemctl enable cs16-server\" to start server on boot"
}

selinux_fix() {
    semanage fcontext -a -t bin_t "/home/${server_user}/.steam/cs16/hlds_run"
    restorecon -v "/home/${server_user}/.steam/cs16/hlds_run"
}

case "$1" in
    "remove")
        remove_server
        ;;
    "")
        check_depends

        install_stage_one
        su "${server_user}" -c "$(declare -f install_stage_two); install_stage_two"
        install_stage_three

        rm -vrf "${tmp_dir}"

        [[ -x "$(command -v semanage)" ]] && selinux_fix
        [[ -x "$(command -v systemctl)" ]] && install_service

        printf "\nhlds parameters can be set in /etc/hlds/cs16-server.conf\n"
        printf "\nInstallation completed\n\n"
        ;;
esac
