#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	printf '\nRun this script as root'
	printf '\nPass remove arg to uninstall\n\n'
	exit 1
fi

server_user=hlds

if [ "$1" = remove ]; then
	if [ -n "$(pgrep hlds)" ]; then
		printf 'Server is running\n'
		printf 'Stop it before uninstalling it\n'
		exit 1
	fi
	rm -vrf /home/${server_user:?}
	rm -vrf /etc/hlds
	rm -vf /var/spool/mail/${server_user}
	rm -vf /usr/share/man/man1/cs16-server.1.gz
	rm -vf /usr/bin/cs16-server
	if [ -n "$(command -v systemctl)" ]; then
		rm -vf /usr/lib/systemd/system/cs16-server.service
	elif [ -n "$(command -v openrc-run)" ]; then
		rm -vf /etc/init.d/cs16-server
	fi
	userdel -f $server_user
	exit 0
elif [ -n "$1" ]; then
	exit 1
fi

grep -q "^$server_user" /etc/passwd && printf "\nServer is already installed\n\n" && exit 1

ctrl_c() {
	killall -s SIGINT steamcmd > /dev/null 2>&1
	printf '\n\nInstallation aborted\n\n'
	exit 1
}

trap ctrl_c INT

lib32_warn() {
	printf '\nInstall 32 bit libstdc++\n'
	printf 'README.md for more info\n\n'
	exit 1
}

if [ -n "$(command -v pacman)" ] || [ -n "$(command -v apt)" ]; then
	if [ ! -d /usr/lib32 ] || [ "$(find /usr/lib32 -type f | grep libstdc++)" = "" ]; then
		lib32_warn
	fi
elif [ -n "$(command -v dnf)" ]; then
	if [ "$(find /usr/lib -type f | grep libstdc++)" = "" ]; then
		lib32_warn
	fi
else
	stty -echo
	printf '\nUnknown distro, make sure you have 32 bit libstdc++\n'
	printf 'Press Enter to continue\n'
	while IFS= read -r line; do
		if [ -z "$line" ]; then
			break
		fi
	done
	stty echo
fi

set -- tar xz gzip curl

for pkg in "$@"; do
	if  [ -z "$(command -v "$pkg")" ]; then
		to_install="$to_install $pkg"
	fi
done

if [ -n "$to_install" ]; then
	printf '\nInstall%s\n\n' "$to_install"
	exit 1
fi

set -- \
https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz \
https://github.com/Bots-United/metamod-p/releases/download/v1.21p38/metamod_i686_linux_win32-1.21p38.tar.xz \
https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux.tar.gz \
https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-cstrike-linux.tar.gz \
https://github.com/yapb/yapb/releases/download/4.4.957/yapb-4.4.957-linux.tar.xz

git_dir=$(pwd)

mkdir -vm 755 /tmp/cs16-server
cd /tmp/cs16-server || exit

for link in "$@"; do
	printf "==> Downloading %s\n" "$link"
	curl -fLO "$link" && continue
	printf "Failed to download %s\n" "$link"
	exit 1
done

cd "$git_dir" || exit

chmod -v 644 /tmp/cs16-server/*

useradd -m -s /usr/bin/sh $server_user
chmod 700 /home/$server_user
passwd -l $server_user

install -vm 755 cs16-server/cs16-server -t /usr/bin
install -vDm 644 cs16-server/cs16-server.conf -t /etc/hlds
install -vm 644 man/cs16-server.1.gz -t /usr/share/man/man1

cp -vf install-stage-two /tmp/install-stage-two
chmod -v 755 /tmp/install-stage-two

su $server_user -c /tmp/install-stage-two

if [ -f "/home/$server_user/.steam/cs16/cstrike/banned.cfg" ]; then
	if [ -n "$(command -v systemctl)" ]; then
		if [ -n "$(command -v sestatus)" ]; then
			install -vm 644 service/selinux/systemd/cs16-server.service -t /usr/lib/systemd/system
		else
			install -vm 644 service/systemd/cs16-server.service -t /usr/lib/systemd/system
		fi
		printf '\nRun systemctl enable cs16-server to start server on boot'
	elif [ -n "$(command -v openrc-run)" ]; then
		if [ -n "$(command -v sestatus)" ]; then
			install -vm 755 service/selinux/openrc/cs16-server -t /etc/init.d
		else
			install -vm 755 service/openrc/cs16-server -t /etc/init.d
		fi
		printf '\nRun rc-update add cs16-server to start server on boot'
	fi
	printf '\nInstallation completed\n\n'
fi
