#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	printf 'Use sudo to run this script\n'
	exit 1
fi

server_user=hlds
server_conf=/etc/hlds/cs16-server.conf
server_workdir=/home/$server_user/.steam
server_params=
server_dll=

_read_conf() {
	while read -r line || [ -n "$line" ]; do
		eval "$line"
	done < "$server_conf"
}

_start_hlds() {
	su "$server_user" -c "cd $server_workdir/cs16 && ./hlds_run ${server_params} ${server_dll} &> /dev/null &"
}

_kill_hlds() {
	su "$server_user" -c "killall -s SIGINT hlds_run hlds_linux &> /dev/null"
}

_update_hlds() {
	su "$server_user" -c "cd $server_workdir && ./steamcmd.sh +force_install_dir cs16 +login anonymous +app_update 90 validate +quit"
}

start_server() {
	if [ -n "$(pgrep hlds)" ]; then
		printf 'Server is already running\n'
		exit 1
	fi
	printf 'Starting server\n'
	_read_conf && _start_hlds
}

stop_server() {
	if [ -z "$(pgrep hlds)" ]; then
		printf 'Server is not running\n'
		exit 1
	fi
	printf 'Stopping server\n'
	_kill_hlds
}

restart_server() {
	if [ -n "$(pgrep hlds)" ]; then
		printf 'Restarting server\n'
		_kill_hlds
	else
		printf 'Starting server\n'
	fi
	_read_conf && _start_hlds
}

update_server() {
	if [ -n "$(pgrep hlds)" ]; then
		printf 'Stop server first\n'
		exit 1
	fi
	printf 'Updating server\n'
	_update_hlds
}

status_server() {
	if [ -z "$(pgrep hlds)" ]; then
		printf 'Server is not running\n'
	else
		printf 'Server is running with the following args:\n'
		pgrep -a hlds_linux | awk '{$1=""}1' | awk '{$1=$1}1'
	fi
}

print_help() {
	printf 'Usage: %s [start | restart | stop | update | status]\n' "$(basename "$0")"
	exit 1
}

case $1 in
	start) start_server;;
	restart) restart_server;;
	stop) stop_server;;
	update) update_server;;
	status) status_server;;
	*) print_help;;
esac
